#!/usr/bin/env xcrun -sdk macosx swift

//
//  main.swift
//  Money
//
//  Created by Nick Baicoianu on 3/14/26.
//

import Foundation

// MARK: - Main()
#if os(macOS)
let process = Process()

let pathToSourceCodeFile = "\(process.currentDirectoryPath)/Sources/Autogenerated.swift"
generateSourceCode(to: pathToSourceCodeFile)

let pathToUnitTestsFile = "\(process.currentDirectoryPath)/Tests/AutogeneratedTests.swift"
generateUnitTests(to: pathToUnitTestsFile)
#else
print("This is a macOS-only tool.", stderr)
#endif
